// Auto-generated by scripts/generate-data.ts — do not edit
// Run "npm run generate" to regenerate

import type { CharacterEntry } from "./types.js";
import data from "./characters.json";

export const characters: CharacterEntry[] = data as CharacterEntry[];
