// Auto-generated by scripts/generate-data.ts — do not edit
// Run "npm run generate" to regenerate

import type { EmojiVariant } from "./types.js";
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
import data from "./variants.json";

export const variants: Record<string, EmojiVariant[]> = data as Record<
  string,
  EmojiVariant[]
>;
